<?php

namespace Devbanana\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{

    public function sumBudgetedAccounts()
    {
        // TODO: Accounts are not yet categorized as budgeted or not budgeted

        $qb = $this->createQueryBuilder('a');
        $query = $qb
            ->select('a.balance')
            ->getQuery()
            ;

        $results = $query->getResult();

        $balance = '0.00';

        foreach ($results as $result)
        {
            $balance = bcadd($balance, $result['balance'], 2);
        }

        return $balance;
    }

}
