<?php

namespace Devbanana\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Devbanana\BudgetBundle\Entity\MasterCategory;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function getHighestOrderFor(MasterCategory $masterCategory)
    {
        $qb = $this->createQueryBuilder('c');
            $query = $qb
                ->where($qb->expr()->eq('c.masterCategory', ':master_category'))
            ->setParameter('master_category', $masterCategory)
            ->orderBy('c.order', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ;

        $result = $query->getOneOrNullResult();

        if ($result) {
            return $result->getOrder();
        }
        else {
            return 0;
        }
    }

    public function findAllOrderedByOrder()
    {
        $qb = $this->createQueryBuilder('c');
        $query = $qb
            ->orderBy('c.order', 'ASC')
            ->getQuery()
            ;

        return $query->getResult();
    }

}
