<?php

namespace Devbanana\BudgetBundle\Entity;

use Devbanana\BudgetBundle\Entity\MasterCategory;
use Devbanana\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function getHighestOrderFor(MasterCategory $masterCategory)
    {
        $qb = $this->createQueryBuilder('c');
            $query = $qb
                ->where($qb->expr()->eq('c.masterCategory', ':master_category'))
            ->setParameter('master_category', $masterCategory)
            ->orderBy('c.order', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ;

        $result = $query->getOneOrNullResult();

        if ($result) {
            return $result->getOrder();
        }
        else {
            return 0;
        }
    }

    public function findAllOrderedByOrder(User $user)
    {
        $query = $this->createQueryBuilder('c')
        ->innerJoin('c.masterCategory', 'mc')
            ->where('mc.user = :user')
            ->setParameter('user', $user)
            ->addOrderBy('mc.order', 'ASC')
            ->addOrderBy('c.order', 'ASC')
            ->getQuery()
            ;

        return $query->getResult();
    }

}
