<?php

namespace Devbanana\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MasterCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterCategoryRepository extends EntityRepository
{

    public function findOrderedMasterCategories()
    {
        $qb = $this->createQueryBuilder('mc');
        $query = $qb
            ->orderBy('mc.order', 'ASC')
            ->getQuery()
            ;

        return $query->getResult();
    }

}
