<?php

namespace Devbanana\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Devbanana\UserBundle\Entity\User;

/**
 * MasterCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MasterCategoryRepository extends EntityRepository
{

    public function findOrderedMasterCategories(User $user)
    {
        $qb = $this->createQueryBuilder('mc');
        $query = $qb
            ->leftJoin('mc.categories', 'c')
            ->select('mc', 'c')
            ->where('mc.user = :user')
            ->setParameter('user', $user)
            ->orderBy('mc.order', 'ASC')
            ->getQuery()
            ;

        return $query->getResult();
    }

}
