<?php

namespace Devbanana\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Devbanana\UserBundle\Entity\User;

/**
 * PayeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayeeRepository extends EntityRepository
{
    public function findAllOrderedByName(User $user)
    {
        $q = $this->createQueryBuilder('p')
            ->where('p.user = :user')
            ->setParameter('user', $user)
            ->orderBy('p.name', 'ASC')
            ->getQuery();

        return $q->getResult();
    }
}
