<?php

namespace Devbanana\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Devbanana\UserBundle\Entity\User;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{

    public function findBetween(\DateTime $month1, \DateTime $month2, User $user)
    {
        $qb = $this->createQueryBuilder('t');
        $query = $qb
            ->leftJoin('t.lineItems', 'l')
            ->select('t', 'l')
            ->where($qb->expr()->andX(
                        $qb->expr()->gte('t.date', ':month1'),
                        $qb->expr()->lt('t.date', ':month2'),
                        $qb->expr()->eq('t.user', ':user')
                        ))
            ->setParameter('month1', $month1)
            ->setParameter('month2', $month2)
            ->setParameter('user', $user)
            ->orderBy('t.date', 'DESC')
            ->getQuery()
            ;

        return $query->getResult();
    }

}
